project:
  type: website
  output-dir: _site

website:
  title: "Melanie Oyarzun"
  favicon: assets/img/star.ico
  search: true
  navbar:
    logo: assets/img/melanieoname.png
    tools:
      - icon: github
        href: https://github.com/melanieoyarzun
      - icon: youtube
        href: https://www.youtube.com/c/MelanieOyarzun
      - icon: envelope
        href: mailto:melanie.oyarzun@gmail.com
    right:
      - href: about.qmd
        text: About
      - href: research/index.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact
  page-footer:
    left: "Melanie Oyarzun"
    right: "Research website built with Quarto"

format:
  html:
    theme:
      - flatly
      - assets/apero-theme.scss
    toc: true
    smooth-scroll: true
    css: styles.css

execute:
  freeze: auto
