baseURL = "https://moyarzun.netlify.app/"
theme = "hugo-apero"
languageCode = "en"
title = "Melanie Oyarzún"
author = "Melanie Oyarzún"
copyright = ""
googleAnalytics = ""
disqusShortname = ""
metaDataFormat = "yaml"
footnoteReturnLinkContents = "&#8617;"
paginate = 6
preserveTaxonomyNames = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
enableEmoji = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true
    hardwraps = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2
    ordered = false
  [markup.highlight]
    style = "github"

[params]
  orgName = "MOW"
  orgLocal = "Budapest, Hungary"
  description = "Postdoctoral Research Fellow at CCL Budapest"
  favicon = "/img/favicon.ico"
  logo = "/img/melanieoname.png"
  mainSections = ["published"]
  navallcaps = true
  socialInHeader = false
  socialInFooter = true
  sharing_image = "/img/0TD3gXMJ.jpeg"
  twitter = "mel2kill"
  theme = "water"
  custom_theme = ""
  customtextFontFamily = "Commissioner"
  customheadingFontFamily = "Fraunces"
  textFontFamily = "sans-serif"
  headingFontFamily = "sans-serif"

  [params.utterances]
    use_utterances = true
    repo_name = "apreshill/apero"
    issue_term = "pathname"
    theme = "boxy-light"
    label = "comments :crystal_ball:"

  [params.math]
    renderer = "katex"

  [[params.social]]
      icon      = "github"
      icon_pack = "fab"
      url       = "https://github.com/melanieoyarzun"

  [[params.social]]
      icon      = "twitter"
      icon_pack = "fab"
      url       = "https://twitter.com/mel2kill"

  [[params.social]]
      icon      = "google-scholar"
      icon_pack = "ai"
      url       = "https://scholar.google.cl/citations?user=5-t0IgkAAAAJ&hl=es"

  [[params.social]]
      icon      = "youtube"
      icon_pack = "fab"
      url       = "https://www.youtube.com/@MelanieOyarzun"

  [[params.social]]
      icon      = "orcid"
      icon_pack = "ai"
      url       = "https://orcid.org/0000-0002-4869-3956"

  [[params.social]]
      icon      = "envelope"
      icon_pack = "fa"
      url       = "mailto:melanie.oyarzun@gmail.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[menu]
  [[menu.header]]
    name = "About"
    title = "About"
    url = "/about/"
    weight = 1

  [[menu.header]]
    name = "Research"
    title = "Research"
    url = "/published/"
    weight = 2

  [[menu.header]]
    name = "Teaching"
    title = "Teaching"
    url = "/teaching/"
    weight = 3

  [[menu.header]]
    name = "CV"
    title = "CV"
    url = "/cv/"
    weight = 4

  [[menu.header]]
    name = "Contact"
    title = "Contact"
    url = "/contact/"
    weight = 5

  [[menu.footer]]
    name = "CV"
    title = "Curriculum Vitae"
    url = "/cv/"
    weight = 1

  [[menu.footer]]
    name = "License"
    title = "License"
    url = "/license/"
    weight = 2

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    disable = false
    anonymizeIP = true
    respectDoNotTrack = true
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
