baseURL = "https://moyarzun.netlify.app/"
theme = "hugo-apero"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
title = "Melanie Oyarzún"
author = "Melanie Oyarzún"
copyright = ""
googleAnalytics = ""
disqusShortname = ""
metaDataFormat = "yaml"
footnoteReturnLinkContents = "&#8617;"
preserveTaxonomyNames = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
enableEmoji = true

[pagination]
  pagerSize = 6

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true
    hardwraps = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2
    ordered = false
  [markup.highlight]
    style = "github"

[params]
  orgName = "MOW"
  orgLocal = "Budapest, Hungary"
  description = "Postdoctoral Research Fellow at CCL Budapest"
  favicon = "/img/favicon.ico"
  logo = "/img/melanieoname.png"
  mainSections = ["published"]
  navallcaps = true
  socialInHeader = false
  socialInFooter = true
  sharing_image = "/img/0TD3gXMJ.jpeg"
  twitter = "mel2kill"
  theme = "water"
  custom_theme = ""
  customtextFontFamily = "Commissioner"
  customheadingFontFamily = "Fraunces"
  textFontFamily = "sans-serif"
  headingFontFamily = "sans-serif"

  [params.utterances]
    use_utterances = false
    repo_name = "melanieoyarzun/melanieoyarzun.github.io"
    issue_term = "pathname"
    theme = "boxy-light"
    label = "comments"

  [params.math]
    renderer = "katex"

  [[params.social]]
      icon      = "linkedin"
      icon_pack = "fab"
      url       = "https://www.linkedin.com/in/melanie-oyarz%C3%BAn-wolf-73789723"

  [[params.social]]
      icon      = "github"
      icon_pack = "fab"
      url       = "https://github.com/melanieoyarzun"

  [[params.social]]
      icon      = "twitter"
      icon_pack = "fab"
      url       = "https://twitter.com/mel2kill"

  [[params.social]]
      icon      = "google-scholar"
      icon_pack = "ai"
      url       = "https://scholar.google.com/citations?user=8Om8OtIAAAAJ&hl=en"

  [[params.social]]
      icon      = "youtube"
      icon_pack = "fab"
      url       = "https://www.youtube.com/@MelanieOyarzun"

  [[params.social]]
      icon      = "orcid"
      icon_pack = "ai"
      url       = "https://orcid.org/0000-0002-4869-3956"

  [[params.social]]
      icon      = "envelope"
      icon_pack = "fa"
      url       = "mailto:melanie.oyarzun@gmail.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[languages]
  [languages.en]
    languageCode = "en-US"
    languageName = "English"
    title = "Melanie Oyarzún"
    weight = 1
    [languages.en.params]
      description = "Postdoctoral Research Fellow at CCL Budapest"
    [languages.en.menus]
      [[languages.en.menus.header]]
        name = "About"
        title = "About"
        pageRef = "/about"
        weight = 1
      [[languages.en.menus.header]]
        name = "Research"
        title = "Research"
        pageRef = "/published"
        weight = 2
      [[languages.en.menus.header]]
        name = "Talks"
        title = "Talks"
        pageRef = "/talk"
        weight = 3
      [[languages.en.menus.header]]
        name = "Teaching"
        title = "Teaching"
        pageRef = "/teaching"
        weight = 4
      [[languages.en.menus.header]]
        name = "CV"
        title = "CV"
        pageRef = "/cv"
        weight = 5
      [[languages.en.menus.header]]
        name = "Contact"
        title = "Contact"
        pageRef = "/contact"
        weight = 6
      [[languages.en.menus.footer]]
        name = "License"
        title = "License"
        pageRef = "/license"
        weight = 1

  [languages.es]
    languageCode = "es-CL"
    languageName = "Español"
    title = "Melanie Oyarzún"
    weight = 2
    [languages.es.params]
      description = "Investigadora postdoctoral en CCL Budapest"
    [languages.es.menus]
      [[languages.es.menus.header]]
        name = "Sobre mí"
        title = "Sobre mí"
        pageRef = "/about"
        weight = 1
      [[languages.es.menus.header]]
        name = "Investigación"
        title = "Investigación"
        pageRef = "/published"
        weight = 2
      [[languages.es.menus.header]]
        name = "Charlas"
        title = "Charlas"
        pageRef = "/talk"
        weight = 3
      [[languages.es.menus.header]]
        name = "Docencia"
        title = "Docencia"
        pageRef = "/teaching"
        weight = 4
      [[languages.es.menus.header]]
        name = "CV"
        title = "CV"
        pageRef = "/cv"
        weight = 5
      [[languages.es.menus.header]]
        name = "Contacto"
        title = "Contacto"
        pageRef = "/contact"
        weight = 6
      [[languages.es.menus.footer]]
        name = "Licencia"
        title = "Licencia"
        pageRef = "/license"
        weight = 1

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    disable = false
    anonymizeIP = true
    respectDoNotTrack = true
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.twitter]
    disable = false
    simple = false
  [privacy.x]
    enableDNT = true
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
